CliffWalking-v0:
  action:
    dim: 1
    num_classes: '4'
    shape: ()
    space: discrete
  observation:
    dim: 1
    is_image_space: false
    num_classes: '48'
    shape: ()
    space: discrete
