HumanoidStandup-v5:
  action:
    dim: 17
    num_classes: '17'
    shape: (17,)
    space: box
  observation:
    dim: 348
    is_image_space: false
    num_classes: '348'
    shape: (348,)
    space: box
