InvertedDoublePendulum-v5:
  action:
    dim: 1
    num_classes: '1'
    shape: (1,)
    space: box
  observation:
    dim: 9
    is_image_space: false
    num_classes: '9'
    shape: (9,)
    space: box
