InvertedDoublePendulum-v4:
  action:
    dim: 1
    num_classes: '1'
    shape: (1,)
    space: box
  observation:
    dim: 11
    is_image_space: false
    num_classes: '11'
    shape: (11,)
    space: box
